package couche_ui;

import com.github.royken.converter.FrenchNumberToWords;
import couche_jpa.Caisse;
import couche_jpa.Centre;
import couche_jpa.Centrebilletage;
import couche_jpa.Departement;
import couche_jpa.Examen;
import couche_jpa.Groupe;
import couche_jpa.Groupedexamen;
import couche_jpa.Jurydel;
import couche_jpa.Nbchefsalle;
import couche_jpa.Region;
import couche_jpa.Rubriquetat;
import couche_jpa.Secteurcouv;
import couche_jpa.Session;
import couche_jpa.Souscentre;
import couche_jpa.Sousfamille;
import couche_metier.IMetier;
import exception.ObcbudgetException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class VueEtatDeliberation1 extends javax.swing.JFrame {

    public VueEtatDeliberation1() {
        initComponents();
        doMyInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButtonFermer = new javax.swing.JButton();
        jPanelChoixExamen = new javax.swing.JPanel();
        jLabelSession = new javax.swing.JLabel();
        jComboBoxSession = new javax.swing.JComboBox<>();
        jButtonAnnulerChoixExamen = new javax.swing.JButton();
        jLabelNiveauExamen = new javax.swing.JLabel();
        jComboBoxNiveau = new javax.swing.JComboBox<>();
        jLabelType = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelExamen = new javax.swing.JLabel();
        jPanelChoixCentre = new javax.swing.JPanel();
        jLabelRegion = new javax.swing.JLabel();
        jComboBoxRegion = new javax.swing.JComboBox<>();
        jButtonAnnulerChoixCentre = new javax.swing.JButton();
        jLabelDepartement = new javax.swing.JLabel();
        jComboBoxDepartement = new javax.swing.JComboBox<>();
        jLabelNomCentre = new javax.swing.JLabel();
        jComboBoxCentre = new javax.swing.JComboBox<>();
        jPanelNbjurys = new javax.swing.JPanel();
        jButtonCreerJury = new javax.swing.JButton();
        jButtonSupprimerJury = new javax.swing.JButton();
        jButtonListerJurys = new javax.swing.JButton();
        jLabelSousfamille = new javax.swing.JLabel();
        jComboBoxSousfamille = new javax.swing.JComboBox<>();
        jLabelNbjurys = new javax.swing.JLabel();
        jTextFieldNbjurys = new javax.swing.JTextField();
        jPanelGestionEtat = new javax.swing.JPanel();
        jButtonCreerEtats = new javax.swing.JButton();
        jButtonMettreAjourEtats = new javax.swing.JButton();
        jButtonVisualiserEtats = new javax.swing.JButton();
        jButtonSupprimerEtats = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("ETAT DE DELIBERATION D'ADMISSIBILITE (ESTI)");

        jButtonFermer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jPanelChoixExamen.setBackground(new java.awt.Color(102, 255, 153));
        jPanelChoixExamen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choisir un groupe d'examens et une session", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabelSession.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSession.setText("Session :");

        jComboBoxSession.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSessionActionPerformed(evt);
            }
        });

        jButtonAnnulerChoixExamen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAnnulerChoixExamen.setText("Annuler");
        jButtonAnnulerChoixExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerChoixExamenActionPerformed(evt);
            }
        });

        jLabelNiveauExamen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNiveauExamen.setText("Niveau :");

        jComboBoxNiveau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabelType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelType.setText("Type :");

        jComboBoxType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        jLabelExamen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelExamen.setText("Examen(s) :");

        javax.swing.GroupLayout jPanelChoixExamenLayout = new javax.swing.GroupLayout(jPanelChoixExamen);
        jPanelChoixExamen.setLayout(jPanelChoixExamenLayout);
        jPanelChoixExamenLayout.setHorizontalGroup(
            jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixExamenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelExamen)
                    .addComponent(jLabelNiveauExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelChoixExamenLayout.createSequentialGroup()
                        .addComponent(jComboBoxNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(47, 47, 47))
            .addGroup(jPanelChoixExamenLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSession, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonAnnulerChoixExamen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChoixExamenLayout.setVerticalGroup(
            jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixExamenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNiveauExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChoixExamenLayout.createSequentialGroup()
                        .addComponent(jLabelExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelChoixExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSession, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnulerChoixExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelChoixCentre.setBackground(new java.awt.Color(153, 255, 255));
        jPanelChoixCentre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choisir un centre de correction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabelRegion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRegion.setText("Région :");

        jComboBoxRegion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRegionActionPerformed(evt);
            }
        });

        jButtonAnnulerChoixCentre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAnnulerChoixCentre.setText("Annuler");
        jButtonAnnulerChoixCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerChoixCentreActionPerformed(evt);
            }
        });

        jLabelDepartement.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDepartement.setText("Département :");

        jComboBoxDepartement.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartementActionPerformed(evt);
            }
        });

        jLabelNomCentre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNomCentre.setText("Centre de délibération :");

        jComboBoxCentre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCentreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChoixCentreLayout = new javax.swing.GroupLayout(jPanelChoixCentre);
        jPanelChoixCentre.setLayout(jPanelChoixCentreLayout);
        jPanelChoixCentreLayout.setHorizontalGroup(
            jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixCentreLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRegion)
                    .addComponent(jLabelDepartement)
                    .addComponent(jLabelNomCentre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelChoixCentreLayout.createSequentialGroup()
                        .addComponent(jComboBoxDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnnulerChoixCentre)
                        .addGap(53, 53, 53))
                    .addGroup(jPanelChoixCentreLayout.createSequentialGroup()
                        .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanelChoixCentreLayout.setVerticalGroup(
            jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChoixCentreLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnulerChoixCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelChoixCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNbjurys.setBackground(new java.awt.Color(255, 204, 204));
        jPanelNbjurys.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jurys par sous-famille de séries/spécialités", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jButtonCreerJury.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCreerJury.setText("Créer");
        jButtonCreerJury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerJuryActionPerformed(evt);
            }
        });

        jButtonSupprimerJury.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSupprimerJury.setText("Supprimer");
        jButtonSupprimerJury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerJuryActionPerformed(evt);
            }
        });

        jButtonListerJurys.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonListerJurys.setText("Lister");
        jButtonListerJurys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListerJurysActionPerformed(evt);
            }
        });

        jLabelSousfamille.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSousfamille.setText("Sous-famille :");

        jComboBoxSousfamille.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jComboBoxSousfamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSousfamilleActionPerformed(evt);
            }
        });

        jLabelNbjurys.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNbjurys.setText("Nombre jurys:");

        jTextFieldNbjurys.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanelNbjurysLayout = new javax.swing.GroupLayout(jPanelNbjurys);
        jPanelNbjurys.setLayout(jPanelNbjurysLayout);
        jPanelNbjurysLayout.setHorizontalGroup(
            jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNbjurysLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSousfamille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSousfamille, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNbjurys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNbjurys, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanelNbjurysLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jButtonCreerJury)
                .addGap(21, 21, 21)
                .addComponent(jButtonSupprimerJury)
                .addGap(21, 21, 21)
                .addComponent(jButtonListerJurys)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanelNbjurysLayout.setVerticalGroup(
            jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNbjurysLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNbjurys, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNbjurys, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSousfamille, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSousfamille, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNbjurysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSupprimerJury, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonListerJurys, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCreerJury, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelGestionEtat.setBackground(new java.awt.Color(153, 204, 255));
        jPanelGestionEtat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gérer l'état", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jButtonCreerEtats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCreerEtats.setText("Créer");
        jButtonCreerEtats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerEtatsActionPerformed(evt);
            }
        });

        jButtonMettreAjourEtats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonMettreAjourEtats.setText("Mettre à jour");
        jButtonMettreAjourEtats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMettreAjourEtatsActionPerformed(evt);
            }
        });

        jButtonVisualiserEtats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonVisualiserEtats.setText("Visualiser");
        jButtonVisualiserEtats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualiserEtatsActionPerformed(evt);
            }
        });

        jButtonSupprimerEtats.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSupprimerEtats.setText("Supprimer");
        jButtonSupprimerEtats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerEtatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGestionEtatLayout = new javax.swing.GroupLayout(jPanelGestionEtat);
        jPanelGestionEtat.setLayout(jPanelGestionEtatLayout);
        jPanelGestionEtatLayout.setHorizontalGroup(
            jPanelGestionEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionEtatLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButtonCreerEtats)
                .addGap(18, 18, 18)
                .addComponent(jButtonMettreAjourEtats)
                .addGap(18, 18, 18)
                .addComponent(jButtonVisualiserEtats)
                .addGap(18, 18, 18)
                .addComponent(jButtonSupprimerEtats)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanelGestionEtatLayout.setVerticalGroup(
            jPanelGestionEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionEtatLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelGestionEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelGestionEtatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonMettreAjourEtats, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCreerEtats, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSupprimerEtats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVisualiserEtats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("  ET D'ADMISSION (ESG/STT)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelNbjurys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelChoixExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelChoixCentre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelGestionEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFermer)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(349, 349, 349)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelChoixExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelChoixCentre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelNbjurys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jPanelGestionEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );

        jLabel1.getAccessibleContext().setAccessibleName("ETAT CM (PRATIQUE SERIE E)  ET JURYS PRESENTATION DES RAPPORTS DE STAGE (BACC SERIE TI)");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualiserEtatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualiserEtatsActionPerformed
        infoSaisies();
        Map<Centre, ArrayList<Jurydel>> centreJurydelMap = new HashMap<>();//contient les centres chacun avec le tableau de ses jurydel
        Map<Centrebilletage, ArrayList<Centre>> centrebilletageCentresMap = new HashMap<>();//contient chaque centre de billetage avec la liste des centres situés dans ses secteurs de couverture
        ArrayList<String> typesBruts = new ArrayList<>();
        ArrayList<String> typesAconsiderer = new ArrayList<>();
        ArrayList<String> niveauxAconsiderer = new ArrayList<>();
        if (!groupedexamensEnstring.equals("") && !anneeString.equals("---")) {
            anneeSelected = Integer.parseInt(anneeString);
            Rubriquetat rubetat = metier.findRubriquetatByDesignation("VACATIONS DELIBERATION D'ADMISSIBILITE (ESTI) OU D'ADMISSION (ESG/STT)");
            caisses = metier.findAllCaissesD1GroupedexamensDans1RubriquetatEt1Session(rubetat.getDesignation(), anneeSelected, niveauSelected, typeSelected);

            boolean poursuivre = false;
            for (Caisse c : caisses) {
                if (c.getGroupe().getNiveau().equals(niveauSelected) && c.getGroupe().getType().equals(typeSelected)) {
                    poursuivre = true;
                    break;
                }
            }
            if (!poursuivre) {
                JOptionPane.showMessageDialog(this, "Erreur, les états de délibération n'ont pas encore été créés pour ce groupe d'examens !");
            } else {
                String separateur = ", ";
                examensList = groupedexamensEnstring.split(separateur);
                for (int i = 0; i < examensList.length; i++) {
                    for (Examen e : examens) {
                        if (e.getSigle().equals(examensList[i])) {
                            examensSelected.add(e);
                            break;
                        }
                    }
                }
                for (Session s : sessions) {
                    if (s.getAnnee() == anneeSelected) {
                        sessionSelected = s;
                        break;
                    }
                }

                //remplissage de centreJurydelMap
                jurydels = metier.findAllJurydelsD1GroupedexamensD1Session(anneeSelected, niveauSelected, typeSelected);
                centres = metier.findAllCentres();
                if (!jurydels.isEmpty()) {
                    for (Centre centre : centres) {
                        ArrayList<Jurydel> jurydelsList = new ArrayList<>();
                        for (Jurydel jurydel : jurydels) {
                            if (jurydel.getCentre().getNomcent().equals(centre.getNomcent())) {
                                jurydelsList.add(jurydel);
                            }
                        }
                        centreJurydelMap.put(centre, jurydelsList);
                    }
                }

                //recherche des types des examens à utiliser
                for (Examen examen : examensSelected) {
                    System.out.println("Examen=" + examen.getSigle() + " Type=" + examen.getType());
                    if (examen.getType().equals("GEN") && !typesBruts.contains("ESG")) {
                        typesBruts.add("ESG");
                    }
                    if (!typesBruts.contains("ESTP") && (examen.getType().equals("IND") || examen.getType().equals("IND PROF") || examen.getType().equals("STT") || examen.getType().equals("STT PROF"))) {
                        typesBruts.add("ESTP");
                    }
                }
                if (typesBruts.size() == 1 && typesBruts.contains("ESG")) {
                    typesAconsiderer.add("ESG");
                    typesAconsiderer.add("TOUT");
                }
                if (typesBruts.size() == 1 && typesBruts.contains("ESTP")) {
                    typesAconsiderer.add("ESTP");
                    typesAconsiderer.add("TOUT");
                }
                if (typesBruts.size() == 2) {
                    typesAconsiderer.add("ESG");
                    typesAconsiderer.add("ESTP");
                    typesAconsiderer.add("TOUT");
                }
                //recherche des niveaux des examens à utiliser
                if (!niveauSelected.equals("TOUT")) {
                    niveauxAconsiderer.add(niveauSelected);
                    niveauxAconsiderer.add("TOUT");
                }
                if (niveauSelected.equals("TOUT")) {
                    niveauxAconsiderer.add("PROB");
                    niveauxAconsiderer.add("BACC");
                    niveauxAconsiderer.add("TOUT");
                }

                //recherche des centres de billetage
                for (String niveau : niveauxAconsiderer) {
                    for (String type : typesAconsiderer) {
                        List<Centrebilletage> desCentrebilletages = metier.findAllCentrebilletagesD1NiveauD1Type(niveau, type);
                        for (Centrebilletage centrebilletage : desCentrebilletages) {
                            ArrayList<Centre> centresList = new ArrayList<>();
                            if (!centrebilletageCentresMap.containsKey(centrebilletage)) {
                                List<Secteurcouv> secteurs = metier.findAllSecteurscouvD1Centrebilletage(centrebilletage.getEtablissement().getAbreviation());
                                for (Secteurcouv sect : secteurs) {
                                    if (testSiCentre(sect.getSouscentre())) {
                                        Centre centre = metier.findCentreByEtablissement(sect.getSouscentre().getEtablissement().getAbreviation());
                                        if (!centresList.contains(centre)) {
                                            centresList.add(centre);
                                        }
                                    }
                                }
                                centrebilletageCentresMap.put(centrebilletage, centresList);
                            }
                        }
                    }
                }

                if (typeSelected.equals("GEN")) {
                    try {
                        List<Map<String, Object>> datasource = new ArrayList<>();
                        for (Region region : regions) {
                            for (Centrebilletage centrebilletage : centrebilletageCentresMap.keySet()) {
                                int totalMontant = 0;
                                if (region.getNomreg().equals(centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg())) {
                                    ArrayList<Centre> centresList = centrebilletageCentresMap.get(centrebilletage);
                                    for (int i = 0; i < centresList.size(); i++) {
                                        Centre centre = centresList.get(i);
                                        int num = 1;
                                        if (centreJurydelMap.containsKey(centre)) {
                                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                            int nbj = jurydelList.size();
                                            for (int p = 0; p < nbj; p++) {

                                                determinerCoutD1jurydel(jurydelList.get(p));

                                                Map<String, Object> row = new HashMap<>();
                                                row.put("examen", groupedexamensEnstring);
                                                row.put("session", anneeSelected);
                                                row.put("region", region.getNomreg());
                                                row.put("reference", "");
                                                row.put("centrebilletage", centrebilletage.getEtablissement().getAbreviation());
                                                row.put("num", num++);
                                                row.put("centre", centre.getNomcent());
                                                row.put("option", optionAffichee);
                                                row.put("nbjury", nbjurys);
                                                row.put("nbmbres", nbmbres);
                                                row.put("nbvac", nbvac);
                                                row.put("coutvac", coutvac);
                                                row.put("primevice", primevice);
                                                row.put("primeteneurPhys", primeteneurPhys);
                                                row.put("primeteneurNum", primeteneurNum);
                                                row.put("baspage", "OBC/AR/" + centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg());
                                                int totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                                row.put("total", totalArrondi);
                                                totalMontant += totalArrondi;//jasperreport prendra la dernière valeur de totalMontant
                                                row.put("totalMontantEnLettres", FrenchNumberToWords.convert(totalMontant).toUpperCase());
                                                datasource.add(row);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        JRDataSource jRDataSource = new JRBeanCollectionDataSource(datasource);
                        JasperReport jasperReport = JasperCompileManager.compileReport("src\\main\\java\\reports\\etatDeliberation1Report.jrxml");
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jRDataSource);
                        JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);//false empêche jasperviewer de fermer l'appli lorsqu'on le ferme
                        jasperViewer.setVisible(true);
                    } catch (JRException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                if (typeSelected.equals("IND") || typeSelected.equals("IND PROF")) {//cas TI
                    try {
                        List<Map<String, Object>> datasource = new ArrayList<>();
                        for (Region region : regions) {
                            for (Centrebilletage centrebilletage : centrebilletageCentresMap.keySet()) {
                                int totalMontant = 0;
                                if (region.getNomreg().equals(centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg())) {
                                    ArrayList<Centre> centresList = centrebilletageCentresMap.get(centrebilletage);
                                    for (int i = 0; i < centresList.size(); i++) {
                                        Centre centre = centresList.get(i);
                                        int num = 1;
                                        if (centreJurydelMap.containsKey(centre)) {
                                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                            int nbj = jurydelList.size();
                                            for (int p = 0; p < nbj; p++) {

                                                determinerCoutD1jurydel(jurydelList.get(p));

                                                Map<String, Object> row = new HashMap<>();
                                                row.put("titre", "DES VACATIONS DELIBERATION D'ADMISSIBILITE/ADMISSION");
                                                row.put("examen", groupedexamensEnstring);
                                                row.put("session", anneeSelected);
                                                row.put("region", region.getNomreg());
                                                row.put("reference", "");
                                                row.put("centrebilletage", centrebilletage.getEtablissement().getAbreviation());
                                                row.put("num", num++);
                                                row.put("centre", centre.getNomcent());
                                                row.put("option", optionAffichee);
                                                row.put("nbjury", nbjurys);
                                                row.put("nbmbres", nbmbrestotal);
                                                row.put("nbvac", nbvac);
                                                row.put("coutvac", coutvac);
                                                row.put("nbteneurs", nbteneurs);
                                                row.put("baspage", "OBC/AR/" + centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg());
                                                row.put("primeteneurPhys", primeteneurPhys);//pour tous teneurs même numérique
                                                int totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                                row.put("total", totalArrondi);
                                                totalMontant += totalArrondi;//jasperreport prendra la dernière valeur de totalMontant
                                                row.put("totalMontantEnLettres", FrenchNumberToWords.convert(totalMontant).toUpperCase());
                                                datasource.add(row);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        JRDataSource jRDataSource = new JRBeanCollectionDataSource(datasource);
                        JasperReport jasperReport = JasperCompileManager.compileReport("src\\main\\java\\reports\\etatDeliberation1ESTPReport.jrxml");
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jRDataSource);
                        JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);//false empêche jasperviewer de fermer l'appli lorsqu'on le ferme
                        jasperViewer.setVisible(true);
                    } catch (JRException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }
                if (typeSelected.equals("STT") || typeSelected.equals("STT PROF")) {//cas STT
                    try {
                        List<Map<String, Object>> datasource = new ArrayList<>();
                        for (Region region : regions) {
                            for (Centrebilletage centrebilletage : centrebilletageCentresMap.keySet()) {
                                int totalMontant = 0;
                                if (region.getNomreg().equals(centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg())) {
                                    ArrayList<Centre> centresList = centrebilletageCentresMap.get(centrebilletage);
                                    for (int i = 0; i < centresList.size(); i++) {
                                        Centre centre = centresList.get(i);
                                        int num = 1;
                                        if (centreJurydelMap.containsKey(centre)) {
                                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                            int nbj = jurydelList.size();
                                            for (int p = 0; p < nbj; p++) {

                                                determinerCoutD1jurydel(jurydelList.get(p));

                                                Map<String, Object> row = new HashMap<>();
                                                row.put("titre", "DES VACATIONS DE DELIBERATION D'ADMISSION");
                                                row.put("examen", groupedexamensEnstring);
                                                row.put("session", anneeSelected);
                                                row.put("region", region.getNomreg());
                                                row.put("reference", "");
                                                row.put("centrebilletage", centrebilletage.getEtablissement().getAbreviation());
                                                row.put("num", num++);
                                                row.put("centre", centre.getNomcent());
                                                row.put("option", optionAffichee);
                                                row.put("nbjury", nbjurys);
                                                row.put("nbmbres", nbmbrestotal);
                                                row.put("nbvac", nbvac);
                                                row.put("coutvac", coutvac);
                                                row.put("nbteneurs", nbteneurs);
                                                row.put("baspage", "OBC/AR/" + centrebilletage.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg());
                                                row.put("primeteneurPhys", primeteneurPhys);//pour tous teneurs même numérique
                                                int totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                                row.put("total", totalArrondi);
                                                totalMontant += totalArrondi;//jasperreport prendra la dernière valeur de totalMontant
                                                row.put("totalMontantEnLettres", FrenchNumberToWords.convert(totalMontant).toUpperCase());
                                                datasource.add(row);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        JRDataSource jRDataSource = new JRBeanCollectionDataSource(datasource);
                        JasperReport jasperReport = JasperCompileManager.compileReport("src\\main\\java\\reports\\etatDeliberation1ESTPReport.jrxml");
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jRDataSource);
                        JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);//false empêche jasperviewer de fermer l'appli lorsqu'on le ferme
                        jasperViewer.setVisible(true);
                    } catch (JRException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                }

                examensSelected.clear();//on vide
                centreJurydelMap.clear();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez recommencez svp. Les champs examen(s) et session sont obligatoires !");
        }
    }//GEN-LAST:event_jButtonVisualiserEtatsActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jComboBoxSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSessionActionPerformed
        //remplirImputationCombobox();
    }//GEN-LAST:event_jComboBoxSessionActionPerformed

    private void jButtonCreerEtatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerEtatsActionPerformed
        infoSaisies();
        Map<Centre, ArrayList<Jurydel>> centreJurydelMap = new HashMap<>();//contient les centres chacun avec le tableau de ses jurydel
        if (!groupedexamensEnstring.equals("") && !anneeString.equals("---")) {
            Groupe groupe = metier.findGroupeD1NiveauEtD1Type(niveauSelected, typeSelected);
            anneeSelected = Integer.parseInt(anneeString);
            Rubriquetat rubetat = metier.findRubriquetatByDesignation("VACATIONS DELIBERATION D'ADMISSIBILITE (ESTI) OU D'ADMISSION (ESG/STT)");
            caisses = metier.findAllCaissesD1GroupedexamensDans1RubriquetatEt1Session(rubetat.getDesignation(), anneeSelected, niveauSelected, typeSelected);
            if (!caisses.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Erreur, les états de délibération existent déjà pour ce groupe d'examens !");
            } else {
                String separateur = ", ";
                examensList = groupedexamensEnstring.split(separateur);
                for (int i = 0; i < examensList.length; i++) {
                    for (Examen e : examens) {
                        if (e.getSigle().equals(examensList[i])) {
                            examensSelected.add(e);
                            break;
                        }
                    }
                }
                for (Session s : sessions) {
                    if (s.getAnnee() == anneeSelected) {
                        sessionSelected = s;
                        break;
                    }
                }

                //remplissage de centreJurydelMap
                jurydels = metier.findAllJurydelsD1GroupedexamensD1Session(anneeSelected, niveauSelected, typeSelected);
                centres = metier.findAllCentres();
                if (!jurydels.isEmpty()) {
                    for (Centre centre : centres) {
                        ArrayList<Jurydel> jurydelsList = new ArrayList<>();
                        for (Jurydel jurydel : jurydels) {
                            if (jurydel.getCentre().getNomcent().equals(centre.getNomcent())) {
                                jurydelsList.add(jurydel);
                            }
                        }
                        centreJurydelMap.put(centre, jurydelsList);
                    }
                }
                boolean testsicreer = false;
                if (typeSelected.equals("GEN")) {
                    try {
                        for (Centre centre : centreJurydelMap.keySet()) {
                            int net = 0;
                            int totalArrondi = 0;
                            Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                            int nbj = jurydelList.size();
                            for (int p = 0; p < nbj; p++) {
                                determinerCoutD1jurydel(jurydelList.get(p));
                                totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                net += totalArrondi;
                            }
                            metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                            testsicreer = true;
                        }
                    } catch (ObcbudgetException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                    if (testsicreer) {
                        JOptionPane.showMessageDialog(this, "Etats de délibération créés avec succès pour ce groupe d'examens !");
                    }
                }
                if (typeSelected.equals("IND") || typeSelected.equals("IND PROF")) {//cas TI
                    try {
                        for (Centre centre : centreJurydelMap.keySet()) {
                            int net = 0;
                            int totalArrondi = 0;
                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                            int nbj = jurydelList.size();
                            for (int p = 0; p < nbj; p++) {
                                determinerCoutD1jurydel(jurydelList.get(p));
                                totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                net += totalArrondi;
                            }
                            Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                            metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                            testsicreer = true;
                        }
                    } catch (ObcbudgetException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                    if (testsicreer) {
                        JOptionPane.showMessageDialog(this, "Etats de délibération créés avec succès pour ce groupe d'examens !");
                    }
                }
                if (typeSelected.equals("STT") || typeSelected.equals("STT PROF")) {//cas STT
                    try {
                        for (Centre centre : centreJurydelMap.keySet()) {
                            int net = 0;
                            int totalArrondi = 0;
                            ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                            int nbj = jurydelList.size();
                            for (int p = 0; p < nbj; p++) {
                                determinerCoutD1jurydel(jurydelList.get(p));
                                totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                net += totalArrondi;
                            }
                            Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                            metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                            testsicreer = true;
                        }
                    } catch (ObcbudgetException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                    if (testsicreer) {
                        JOptionPane.showMessageDialog(this, "Etats de délibération créés avec succès pour ce groupe d'examens !");
                    }
                }
                examensSelected.clear();//on vide
                centreJurydelMap.clear();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tous les champs sont obligatoires !");
        }
    }//GEN-LAST:event_jButtonCreerEtatsActionPerformed

    private void jButtonMettreAjourEtatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMettreAjourEtatsActionPerformed
        infoSaisies();
        Map<Centre, ArrayList<Jurydel>> centreJurydelMap = new HashMap<>();//contient les centres chacun avec le tableau de ses jurydel
        int result = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier les états de délibération pour ce groupe d'examens ?", "confirmation de modification", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            if (!groupedexamensEnstring.equals("") && !anneeString.equals("---")) {
                anneeSelected = Integer.parseInt(anneeString);
                Rubriquetat rubetat = metier.findRubriquetatByDesignation("VACATIONS DELIBERATION D'ADMISSIBILITE (ESTI) OU D'ADMISSION (ESG/STT)");
                caisses = metier.findAllCaissesD1GroupedexamensDans1RubriquetatEt1Session(rubetat.getDesignation(), anneeSelected, niveauSelected, typeSelected);
                if (caisses.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Erreur, aucun état de délibération n'existe pour ce groupe d'examens !");
                } else {
                    //on conserve quelques info de ces anciennes caisses
                    Groupe groupe = caisses.get(0).getGroupe();
                    sessionSelected = caisses.get(0).getSession();
                    //on supprime toutes les anciennes caisses du groupe d'examens
                    for (Caisse c : caisses) {
                        metier.supprimerCaisse(c);
                    }
                    //on va les recréer
                    String separateur = ", ";
                    examensList = groupedexamensEnstring.split(separateur);
                    for (int i = 0; i < examensList.length; i++) {
                        for (Examen e : examens) {
                            if (e.getSigle().equals(examensList[i])) {
                                examensSelected.add(e);
                                break;
                            }
                        }
                    }

                    //remplissage de centreJurydelMap
                    jurydels = metier.findAllJurydelsD1GroupedexamensD1Session(anneeSelected, niveauSelected, typeSelected);
                    centres = metier.findAllCentres();
                    if (!jurydels.isEmpty()) {
                        for (Centre centre : centres) {
                            ArrayList<Jurydel> jurydelsList = new ArrayList<>();
                            for (Jurydel jurydel : jurydels) {
                                if (jurydel.getCentre().getNomcent().equals(centre.getNomcent())) {
                                    jurydelsList.add(jurydel);
                                }
                            }
                            centreJurydelMap.put(centre, jurydelsList);
                        }
                    }

                    boolean testsimodifier = false;
                    if (typeSelected.equals("GEN")) {
                        try {
                            for (Centre centre : centreJurydelMap.keySet()) {
                                int net = 0;
                                int totalArrondi = 0;
                                Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                                ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                int nbj = jurydelList.size();
                                for (int p = 0; p < nbj; p++) {
                                    determinerCoutD1jurydel(jurydelList.get(p));
                                    totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                    net += totalArrondi;
                                }
                                metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                                testsimodifier = true;
                            }
                        } catch (ObcbudgetException e) {
                            JOptionPane.showMessageDialog(this, e.getMessage());
                        }
                        if (testsimodifier) {
                            JOptionPane.showMessageDialog(this, "Etats de délibération mis à jour avec succès pour ce groupe d'examens !");
                        }
                    }
                    if (typeSelected.equals("IND") || typeSelected.equals("IND PROF")) {//cas TI
                        try {
                            for (Centre centre : centreJurydelMap.keySet()) {
                                int net = 0;
                                int totalArrondi = 0;
                                ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                int nbj = jurydelList.size();
                                for (int p = 0; p < nbj; p++) {
                                    determinerCoutD1jurydel(jurydelList.get(p));
                                    totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                    net += totalArrondi;
                                }
                                Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                                metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                                testsimodifier = true;
                            }
                        } catch (ObcbudgetException e) {
                            JOptionPane.showMessageDialog(this, e.getMessage());
                        }
                        if (testsimodifier) {
                            JOptionPane.showMessageDialog(this, "Etats de délibération mis à jour avec succès pour ce groupe d'examens !");
                        }
                    }
                    if (typeSelected.equals("STT") || typeSelected.equals("STT PROF")) {//cas STT
                        try {
                            for (Centre centre : centreJurydelMap.keySet()) {
                                int net = 0;
                                int totalArrondi = 0;
                                ArrayList<Jurydel> jurydelList = centreJurydelMap.get(centre);
                                int nbj = jurydelList.size();
                                for (int p = 0; p < nbj; p++) {
                                    determinerCoutD1jurydel(jurydelList.get(p));
                                    totalArrondi = (int) Math.ceil((double) total / (double) 1000) * 1000;
                                    net += totalArrondi;
                                }
                                Souscentre souscentre = metier.findSouscentreByEtablissement(centre.getEtablissement().getAbreviation());
                                metier.creerCaisse(new Caisse(net, 0, 0, 0, groupe, rubetat, sessionSelected, souscentre, false));
                                testsimodifier = true;
                            }
                        } catch (ObcbudgetException e) {
                            JOptionPane.showMessageDialog(this, e.getMessage());
                        }
                        if (testsimodifier) {
                            JOptionPane.showMessageDialog(this, "Etats de délibération mis à jour avec succès pour ce groupe d'examens !");
                        }
                    }

                    examensSelected.clear();//on vide
                    centreJurydelMap.clear();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Les champs groupe d'examens et session sont obligatoires !");
            }

        }
    }//GEN-LAST:event_jButtonMettreAjourEtatsActionPerformed

    private void jButtonSupprimerEtatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerEtatsActionPerformed
        infoSaisies();
        int result = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer les états de délibération pour ce groupe d'examens ?", "confirmation de suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            if (!groupedexamensEnstring.equals("") && !anneeString.equals("---")) {
                anneeSelected = Integer.parseInt(anneeString);
                Rubriquetat rubetat = metier.findRubriquetatByDesignation("VACATIONS DELIBERATION D'ADMISSIBILITE (ESTI) OU D'ADMISSION (ESG/STT)");
                caisses = metier.findAllCaissesD1GroupedexamensDans1RubriquetatEt1Session(rubetat.getDesignation(), anneeSelected, niveauSelected, typeSelected);
                if (caisses.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Erreur, aucun état de délibération n'existe pour ce groupe d'examens !");
                } else {
                    boolean testsisupprimer = false;
                    try {
                        for (Caisse caisse : caisses) {
                            metier.supprimerCaisse(caisse);
                        }
                        testsisupprimer = true;
                    } catch (ObcbudgetException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                    if (testsisupprimer) {
                        JOptionPane.showMessageDialog(this, "Etats de délibération supprimés avec succès pour ce groupe d'examens !");
                    }
                }
            }
        }

    }//GEN-LAST:event_jButtonSupprimerEtatsActionPerformed

    private void jButtonAnnulerChoixExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerChoixExamenActionPerformed
        jComboBoxNiveau.setSelectedIndex(0);
        jComboBoxType.setSelectedIndex(0);
        jTextArea1.setText("");
        jComboBoxSession.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonAnnulerChoixExamenActionPerformed

    private void jButtonAnnulerChoixCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerChoixCentreActionPerformed
        jComboBoxRegion.setSelectedIndex(0);
        jComboBoxDepartement.setSelectedIndex(0);
        jComboBoxCentre.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonAnnulerChoixCentreActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        niveauSelected = (String) jComboBoxNiveau.getSelectedItem();
        if (!niveauSelected.equals("---")) {
            remplirExamensTextArea();
        }
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jComboBoxRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRegionActionPerformed
        remplirDepartementCombobox();
    }//GEN-LAST:event_jComboBoxRegionActionPerformed

    private void jButtonCreerJuryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerJuryActionPerformed
        infoSaisies();
        if (groupedexamensEnstring.equals("") || anneeString.equals("---") || nomCentreSelected.equals("---") || titreSousfamilleSelected.equals("---") || nbjurysString.equals("")) {
            JOptionPane.showMessageDialog(this, "Recommencez svp. Vous devez choisir un groupe d'examens, une session, un centre, une sous-famille, donner le nombre de jurys !");
        } else {
            validerNbjurys(nbjurysString);
            if (!continuerNbjurys || nbjurysSaisi == 0) {
                JOptionPane.showMessageDialog(this, "Recommencez svp. Le nombre de jurys fourni est incorrect !");
            } else {
                Groupe groupe = metier.findGroupeD1NiveauEtD1Type(niveauSelected, typeSelected);
                anneeSelected = Integer.parseInt(anneeString);
                for (Session s : sessions) {
                    if (s.getAnnee() == anneeSelected) {
                        sessionSelected = s;
                        break;
                    }
                }
                for (Centre centre : centres) {
                    if (centre.getNomcent().equals(nomCentreSelected)) {
                        centreSelected = centre;
                        break;
                    }
                }

                for (Sousfamille sousfam : sousfamilles) {
                    if (sousfam.getTitre().equals(titreSousfamilleSelected)) {
                        sousfamilleSelected = sousfam;
                        break;
                    }
                }
                try {
                    metier.creerJurydel(new Jurydel(nbjurysSaisi, centreSelected, groupe, sessionSelected, sousfamilleSelected));
                    JOptionPane.showMessageDialog(this, "Nombre de jurys enregistré avec succès !");
                } catch (ObcbudgetException ex) {
                    JOptionPane.showMessageDialog(this, "Impossible de d'enregistrer le nombre de jurys dans le centre [" + nomCentreSelected + "]" + "\n raison:" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButtonCreerJuryActionPerformed

    private void jButtonSupprimerJuryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerJuryActionPerformed
        infoSaisies();
        if (groupedexamensEnstring.equals("") || anneeString.equals("---") || nomCentreSelected.equals("---") || titreSousfamilleSelected.equals("---")) {
            JOptionPane.showMessageDialog(this, "Recommencez svp. Vous devez choisir un groupe d'examens, une session, un centre et une sous-famille !");
        } else {
            int result = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer le nombre de jurys de la sous-famille de séries/spécialités " + titreSousfamilleSelected + " du centre [" + nomCentreSelected + "] ?", "confirmation de suppression", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                anneeSelected = Integer.parseInt(anneeString);
                try {
                    Jurydel jurydel = metier.findJurydelD1SousfamilleD1CentreD1GroupedexamensD1Session(nomCentreSelected, anneeSelected, niveauSelected, typeSelected, titreSousfamilleSelected);
                    metier.supprimerJurydel(jurydel);
                    JOptionPane.showMessageDialog(this, "Nombre de jurys  supprimé avec succès !");
                } catch (ObcbudgetException ex) {
                    JOptionPane.showMessageDialog(this, "Impossible de supprimer le nombre de jurys de la sous-famille " + titreSousfamilleSelected + " du centre [" + nomCentreSelected + "] \n raison:" + ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButtonSupprimerJuryActionPerformed

    private void jButtonListerJurysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListerJurysActionPerformed
        infoSaisies();
        Map<Centre, ArrayList<Jurydel>> centreJurydelMap = new HashMap<>();//contient les centres chacun avec le tableau de ses jurydel
        if (groupedexamensEnstring.equals("") || anneeString.equals("---")) {
            JOptionPane.showMessageDialog(this, "Recommencez svp. Vous devez choisir un groupe d'examens et une session !");
        } else {
            anneeSelected = Integer.parseInt(anneeString);
            //remplissage de centreJurydelMap
            jurydels = metier.findAllJurydelsD1GroupedexamensD1Session(anneeSelected, niveauSelected, typeSelected);
            centres = metier.findAllCentres();
            if (!jurydels.isEmpty()) {
                for (Centre centre : centres) {
                    ArrayList<Jurydel> jurydelsList = new ArrayList<>();
                    for (Jurydel jurydel : jurydels) {
                        if (jurydel.getCentre().getNomcent().equals(centre.getNomcent())) {
                            jurydelsList.add(jurydel);
                        }
                    }
                    centreJurydelMap.put(centre, jurydelsList);
                }
            }

            if (!jurydels.isEmpty()) {
                try {
                    List<Map<String, Object>> datasource = new ArrayList<Map<String, Object>>();
                    for (Region region : regions) {
                        int i = 1;
                        for (Centre centre : centreJurydelMap.keySet()) {
                            if (centre.getEtablissement().getArrondissement().getDepartement().getRegion().getNomreg().equals(region.getNomreg())) {
                                for (Jurydel jurydel : centreJurydelMap.get(centre)) {
                                    Map<String, Object> row = new HashMap<>();
                                    row.put("session", anneeSelected);
                                    row.put("examen", groupedexamensEnstring);
                                    row.put("region", region.getNomreg());
                                    row.put("num", i++);
                                    row.put("centre", jurydel.getCentre().getNomcent());
                                    row.put("sousfamille", jurydel.getSousfamille().getTitre());
                                    row.put("nbjury", jurydel.getNbjurydel());
                                    datasource.add(row);
                                }
                            }
                        }
                    }
                    JRDataSource jRDataSource = new JRBeanCollectionDataSource(datasource);
                    JasperReport jasperReport = JasperCompileManager.compileReport("src\\main\\java\\reports\\etatListeJurydelReport.jrxml");
                    JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jRDataSource);
                    JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);//false empêche jasperviewer de fermer l'appli lorsqu'on le ferme
                    jasperViewer.setVisible(true);
                } catch (JRException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Aucun nombre de jurys trouvé dans la base de données !");
            }
        }
    }//GEN-LAST:event_jButtonListerJurysActionPerformed

    private void jComboBoxDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartementActionPerformed
        remplirCentreCombobox();

    }//GEN-LAST:event_jComboBoxDepartementActionPerformed

    private void jComboBoxCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCentreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCentreActionPerformed

    private void jComboBoxSousfamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSousfamilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSousfamilleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueEtatDeliberation1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueEtatDeliberation1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueEtatDeliberation1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueEtatDeliberation1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueEtatDeliberation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAnnulerChoixCentre;
    private javax.swing.JButton jButtonAnnulerChoixExamen;
    private javax.swing.JButton jButtonCreerEtats;
    private javax.swing.JButton jButtonCreerJury;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonListerJurys;
    private javax.swing.JButton jButtonMettreAjourEtats;
    private javax.swing.JButton jButtonSupprimerEtats;
    private javax.swing.JButton jButtonSupprimerJury;
    private javax.swing.JButton jButtonVisualiserEtats;
    private javax.swing.JComboBox<String> jComboBoxCentre;
    private javax.swing.JComboBox<String> jComboBoxDepartement;
    private javax.swing.JComboBox<String> jComboBoxNiveau;
    private javax.swing.JComboBox<String> jComboBoxRegion;
    private javax.swing.JComboBox<String> jComboBoxSession;
    private javax.swing.JComboBox<String> jComboBoxSousfamille;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDepartement;
    private javax.swing.JLabel jLabelExamen;
    private javax.swing.JLabel jLabelNbjurys;
    private javax.swing.JLabel jLabelNiveauExamen;
    private javax.swing.JLabel jLabelNomCentre;
    private javax.swing.JLabel jLabelRegion;
    private javax.swing.JLabel jLabelSession;
    private javax.swing.JLabel jLabelSousfamille;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelChoixCentre;
    private javax.swing.JPanel jPanelChoixExamen;
    private javax.swing.JPanel jPanelGestionEtat;
    private javax.swing.JPanel jPanelNbjurys;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNbjurys;
    // End of variables declaration//GEN-END:variables

    // variables d'instance
    private IMetier metier = null;
    private List<Session> sessions = null;
    private List<Region> regions = null;
    private List<Examen> examens = null;
    private Examen examenSelected = null;
    private String[] examensList = null;
    private List<Examen> examensSelected = new ArrayList<>();
    private List<Departement> departements = null;
    private String[] sessionsCombo = null;
    private String[] regionsCombo = null;
    private String[] departementsCombo = null;
    private String[] centresCombo = null;
    private String[] sousfamillesCombo = null;
    private String nomRegionSelected = "";
    private String nomCentreSelected = "";
    private String nomDepartementSelected = "";
    private String titreSousfamilleSelected = "";
    private List<Centre> centres = null;
    private Centre centreSelected = null;
    private List<Sousfamille> sousfamilles = null;
    private Sousfamille sousfamilleSelected = null;
    private int anneeSelected = 0;
    private String anneeString = "";
    private Session sessionSelected = null;
    private List<Caisse> caisses = null;
    private String niveauSelected = "";
    private String typeSelected = "";
    private String[] typesCombo = null;
    private String[] niveauxCombo = null;
    private String groupedexamensEnstring = "";
    private List<Groupedexamen> groupedexamens = null;
    private int nbmat = 0, nbmbres = 0, nbmbrestotal = 0, nbjurys = 0, nbteneurs = 0, nbvac = 0, txvac = 1500, coutvac = 0, primevice = 0, primeteneurPhys = 0, primeteneurNum = 0, total;
    private String optionAffichee = "";
    private boolean continuerNbjurys = false;
    private int nbjurysSaisi = 0;
    private String nbjurysString = "";
    private List<Jurydel> jurydels = null;

    //private boolean valBoutonRadioNbchefsalle = false;
    //private boolean valBoutonRadioNbcopies = false;
    private void doMyInit() {
        // init contexte
        // instanciation couche [metier]
        ApplicationContext ctx = new ClassPathXmlApplicationContext("spring-config-metier.xml");
        metier = (IMetier) ctx.getBean("metier");
        sessions = metier.findAllSessions();
        regions = metier.findAllRegions();
        examens = metier.findAllExamens();
        centres = metier.findAllCentres();
        sousfamilles = metier.findAllSousfamilles();

        //on remplit la combobox des régions du sous-centre
        regionsCombo = new String[regions.size() + 1];
        regionsCombo[0] = "---";
        int i = 1;
        for (Region region : regions) {
            regionsCombo[i++] = region.getNomreg();
        }
        jComboBoxRegion.setModel(new DefaultComboBoxModel(regionsCombo));

        //on remplit la combobox des sessions
        sessionsCombo = new String[sessions.size() + 1];
        sessionsCombo[0] = "---";
        int k = 1;
        for (Session session : sessions) {
            if (!session.isCloturee()) {
                sessionsCombo[k++] = "" + session.getAnnee();
            }
        }
        jComboBoxSession.setModel(new DefaultComboBoxModel(sessionsCombo));

        //on remplit la combobox des sousfamilles
        sousfamillesCombo = new String[sousfamilles.size() + 1];
        sousfamillesCombo[0] = "---";
        int l = 1;
        for (Sousfamille sousfamille : sousfamilles) {
            sousfamillesCombo[l++] = sousfamille.getTitre();
        }
        jComboBoxSousfamille.setModel(new DefaultComboBoxModel(sousfamillesCombo));

        //on remplit la combobox des types
        typesCombo = new String[]{"---", "GEN", "IND", "IND PROF", "STT", "STT PROF"};
        jComboBoxType.setModel(new DefaultComboBoxModel(typesCombo));

        //on remplit la combobox des niveaux
        niveauxCombo = new String[]{"---", "PROB", "BACC"};
        jComboBoxNiveau.setModel(new DefaultComboBoxModel(niveauxCombo));

        remplirDepartementCombobox();
        remplirCentreCombobox();
    }

    private void infoSaisies() {
        niveauSelected = (String) jComboBoxNiveau.getSelectedItem();
        typeSelected = (String) jComboBoxType.getSelectedItem();
        nomCentreSelected = (String) jComboBoxCentre.getSelectedItem();
        groupedexamensEnstring = jTextArea1.getText();
        anneeString = (String) jComboBoxSession.getSelectedItem();
        titreSousfamilleSelected = (String) jComboBoxSousfamille.getSelectedItem();
        nbjurysString = jTextFieldNbjurys.getText();
    }

    private void remplirDepartementCombobox() {
        nomRegionSelected = (String) jComboBoxRegion.getSelectedItem();
        departements = metier.findAllDepartementsD1Region(nomRegionSelected);
        //on remplit la combobox des départements
        departementsCombo = new String[departements.size() + 1];
        departementsCombo[0] = "---";
        int i = 1;
        for (Departement departement : departements) {
            departementsCombo[i++] = departement.getNomdepart();
        }
        jComboBoxDepartement.setModel(new DefaultComboBoxModel(departementsCombo));
    }

    private void remplirCentreCombobox() {
        nomDepartementSelected = (String) jComboBoxDepartement.getSelectedItem();
        centres = metier.findAllCentresD1Departement(nomDepartementSelected);
        //on remplit la combobox des sous-centres
        centresCombo = new String[centres.size() + 1];
        centresCombo[0] = "---";
        int i = 1;
        for (Centre centre : centres) {
            centresCombo[i++] = centre.getNomcent();
        }
        jComboBoxCentre.setModel(new DefaultComboBoxModel(centresCombo));

    }

    private void validerNbjurys(String nbreString) {
        try {
            nbjurysSaisi = Integer.parseInt(nbreString);
            continuerNbjurys = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Le nombre de jurys doit être fourni et contenir uniquement des chiffres entiers!");
            continuerNbjurys = false;
        }
    }

    private void determinerCoutD1jurydel(Jurydel jurydel) {
        if (niveauSelected.equals("BACC") && typeSelected.equals("GEN")) {
            //toutes les séries ont 11 comme nombre de matières dont de membres de jurys de délibération
            //sauf C (12)
            //avec C/E c'est C (12) qui l'emporte

            nbmat = 11;

            if ((testSiTitreSousfamilleContient1Sigle(jurydel.getSousfamille(), "D") || testSiTitreSousfamilleContient1Sigle(jurydel.getSousfamille(), "TI")) && !jurydel.getSousfamille().getTitre().equals("A4-CHI") && !jurydel.getSousfamille().getTitre().equals("ALL-CHI-ITA") && !jurydel.getSousfamille().getTitre().equals("ESP-CHI-ITA") && !jurydel.getSousfamille().getTitre().equals("ABI-CHI") && !jurydel.getSousfamille().getTitre().equals("A5-ES-CHI") && !jurydel.getSousfamille().getTitre().equals("ARA-CHI-ITA-ALL")) {
                nbmat = 12;
            }

            optionAffichee = jurydel.getSousfamille().getTitre();
            nbjurys = jurydel.getNbjurydel();
            nbmbres = (nbmat - 3) * nbjurys;
            nbvac = nbmbres * 8;//8 vacations
            coutvac = nbvac * txvac;
            primevice = 32000 * nbjurys;
            primeteneurPhys = 22000 * nbjurys;
            primeteneurNum = 32000 * nbjurys;
        }
        if (niveauSelected.equals("PROB") && typeSelected.equals("GEN")) {
            //ici au PROB ESG, jurydel est composé de 6 jurys qu'on divise en 2 groupes
            //chaque groupe de 3 jurys possède 12 membres dont le vice-PJ (1er teneur PV physique)
            //le teneur PV numérique et le 2ème teneur PV physique
            //c'est donc dire que chaque PJ a 2 vices-PJ (1er teneur PV physique), 2 teneurs numérique et 2 2ème teneurs PV physique
            //on a: 12membres-3teneurs= 9 membres par groupe
            //et donc 9x2= 18=3x6 membres par jurydel et 6 teneurs (2 vices-PJ, 2 teneurs num et 2 teneurs phys) 
            optionAffichee = jurydel.getSousfamille().getTitre();
            nbjurys = jurydel.getNbjurydel();
            nbmbres = 18;
            nbvac = nbmbres * 10;//10 vacations
            coutvac = nbvac * txvac;
            primevice = 40000 * 2;//2 groupes de 3 jurys
            primeteneurPhys = 30000 * 2;//2 groupes de 3 jurys
            primeteneurNum = 32000 * 2;
        }
        if (typeSelected.equals("IND") || typeSelected.equals("IND PROF")) {
            nbmbres = 12;
            nbmbrestotal = 0;
            /*
            if (jurydel.getSousfamille().getTitre().equals("F3") || jurydel.getSousfamille().getTitre().equals("GT") || jurydel.getSousfamille().getTitre().equals("CMA-MVT") || jurydel.getSousfamille().getTitre().equals("MEB") || jurydel.getSousfamille().getTitre().equals("F1") || jurydel.getSousfamille().getTitre().equals("F5") || jurydel.getSousfamille().getTitre().equals("F8") || jurydel.getSousfamille().getTitre().equals("ISRH") || jurydel.getSousfamille().getTitre().equals("CMA-MVT MVPL") || jurydel.getSousfamille().getTitre().equals("MISE") || jurydel.getSousfamille().getTitre().equals("F7-BIOLAP BIOTECH")) {
                nbmbres = 8;
            }
            if (jurydel.getSousfamille().getTitre().equals("F4-BA") || jurydel.getSousfamille().getTitre().equals("CHTI") || jurydel.getSousfamille().getTitre().equals("IH")) {
                nbmbres = 9;
            }
            if (jurydel.getSousfamille().getTitre().equals("AF1") || jurydel.getSousfamille().getTitre().equals("AF2") || jurydel.getSousfamille().getTitre().equals("AF3") || jurydel.getSousfamille().getTitre().equals("F6-BIPE") || jurydel.getSousfamille().getTitre().equals("F6-COPH") || jurydel.getSousfamille().getTitre().equals("F6-MIPE")) {
                nbmbres = 2;
            }
            if (jurydel.getSousfamille().getTitre().equals("MHB") || jurydel.getSousfamille().getTitre().equals("MEM") || jurydel.getSousfamille().getTitre().equals("AG") || jurydel.getSousfamille().getTitre().equals("TGF") || jurydel.getSousfamille().getTitre().equals("IB")) {
                nbmbres = 5;
            }
            if (jurydel.getSousfamille().getTitre().equals("BIJO")) {
                nbmbres = 3;
            }
            if (jurydel.getSousfamille().getTitre().equals("F4-BE") || jurydel.getSousfamille().getTitre().equals("F4-TP")) {
                nbmbres = 6;
            }
             */
            optionAffichee = jurydel.getSousfamille().getTitre();
            nbjurys = jurydel.getNbjurydel();
            nbteneurs = nbjurys * 3;
            nbmbrestotal = nbmbres * nbjurys;
            nbvac = nbmbrestotal * 8;//8 vacations
            coutvac = nbvac * txvac;
            primevice = 0;//cette notion n'existe pas ici. tous les teneurs ont 15000
            primeteneurPhys = nbteneurs * 15000;//pour tous les teneurs
            primeteneurNum = 0;
        }
        if (typeSelected.equals("STT") || typeSelected.equals("STT PROF")) {
            nbmbrestotal = 0;
            nbmbres = 12;
            /*
            if (testSiTitreSousfamilleContient1Sigle(jurydel.getSousfamille(),"ESF") || testSiTitreSousfamilleContient1Sigle(jurydel.getSousfamille(),"HO")) {
                nbmbres = 12;
            }
            if (testSiTitreSousfamilleContient1Sigle(jurydel.getSousfamille(),"SES ALL-ESP-CHI")) {
                nbmbres = 8;
            }
             */
            optionAffichee = jurydel.getSousfamille().getTitre();
            nbjurys = jurydel.getNbjurydel();
            nbmbrestotal = nbmbres * nbjurys + 10;//10 membres pour EG
            nbteneurs = nbjurys * 3;
            nbvac = nbmbrestotal * 8;//8 vacations
            coutvac = nbvac * txvac;
            primevice = 0;//cette notion n'existe pas ici. tous les teneurs ont 15000
            primeteneurPhys = nbteneurs * 15000;//pour tous les teneurs
            primeteneurNum = 0;
        }

        total = coutvac + primevice + primeteneurPhys + primeteneurNum;
    }

    private void remplirExamensTextArea() {
        typeSelected = (String) jComboBoxType.getSelectedItem();
        String examensSelectedEnchaine = "";
        if (typeSelected.equals("---")) {
            JOptionPane.showMessageDialog(this, "Le champ Type est vide !");
        } else {
            groupedexamens = metier.findAllGroupedexamensD1NiveauEtD1Type(niveauSelected, typeSelected);
            int i = 0;
            for (Groupedexamen g : groupedexamens) {
                if (i++ == 0) {
                    examensSelectedEnchaine += g.getExamen().getSigle();
                } else {
                    examensSelectedEnchaine += ", " + g.getExamen().getSigle();
                }
            }
            jTextArea1.setText(examensSelectedEnchaine);
            jTextArea1.setLineWrap(true);//renvoyer automatiquement le texte à la ligne dans le textArea
        }
    }

    private boolean testSiTitreSousfamilleContient1Sigle(Sousfamille sousfamille, String sigle) {
        boolean testeur = false;
        List<Sousfamille> lesSousfamilles = metier.findAllSousfamillesLikeTitre(sigle);//si un sous-centre possède un jury dont la sous-famille contient un sigle, cette sous-famille y est unique
        for (Sousfamille sf : lesSousfamilles) {
            if (sf.getTitre().equals(sousfamille.getTitre())) {
                testeur = true;
                break;
            }
        }
        return testeur;
    }

    private boolean testSiCentre(Souscentre souscentre) {
        boolean result = false;
        centres = metier.findAllCentres();
        for (Centre centre : centres) {
            if (centre.getEtablissement().getAbreviation().equals(souscentre.getEtablissement().getAbreviation())) {
                result = true;
                break;
            }
        }
        return result;
    }

}
